#!/bin/bash

set -e  # إيقاف السكربت عند حدوث أي خطأ

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "ali9313" ]]; then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2FsaTkzMTMvbGlvL2FyY2hpdmUvSHVSZS56aXA" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]; then
        if [[ $UPSTREAM_REPO_BRANCH ]]; then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/HuRe.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2FsaTkzMTMvbGlvL2FyY2hpdmUvSHVSZS56aXA=" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "ali9313" ]]; then
        rlink=$(echo "aHR0cHM6Ly9naXRodWIuY29tL2FsaTkzMTMvYWxpLmdpdA==" | base64 -d)
    elif [[ $UPSTREAM_REPO =~ $regex ]]; then
        rlink=$(echo "${UPSTREAM_REPO}")
    else
        rlink=$(echo "aHR0cHM6Ly9naXRodWIuY29tL2plcHRob25pcS9qZXB0aG9uLmdpdA==" | base64 -d)
    fi
    echo "$rlink"
}

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpack_git() {
    _run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/ali9313/lio"
ACTIVE_BRANCH_NAME = "HuRe"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True)'
}

_run_cat_git() {
    local repolink=$(_get_repolink)
    _run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'${UPSTREAM_REPO_BRANCH:-HuRe}'"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True)'
}

_set_bot () {
    local zippath
    zippath="aliup.zip"
    
    echo "جاري تنزيل اكواد السورس..."
    wget -q $(_get_ziplink) -O "$zippath"
    
    echo "تفريغ البيانات..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.")
    unzip -qq "$zippath"
    echo "تم التفريغ."
    
    echo "يتم التنظيف..."
    rm -rf "$zippath"
    sleep 5
    
    _run_catpack_git
    cd "$CATPATH"
    _run_cat_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    
    echo "بدء تنزيل بيانات ꪖꪶ𝓲..."
    python3 -m aliup
}

# تأكد من تعيين المتغيرات قبل استدعاء الدالة
echo "UPSTREAM_REPO: $UPSTREAM_REPO"
echo "UPSTREAM_REPO_BRANCH: $UPSTREAM_REPO_BRANCH"

_set_bot
